version: '3'

networks:
  laravel:

services:
  nginx:
    container_name: mynginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
      - redis
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laraveldocker
      MYSQL_USER: root
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - laravel-data:/data/db
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: composer install -d /var/www/html

    depends_on:
      - app
    networks:
      - laravel
  echo:
    build:
      context: ./echo
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6001:6001"
    networks:
      - laravel
volumes:
  laravel-data:

